# Generated by Django 3.1.7 on 2021-04-26 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlog',
            name='product',
            field=models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='dummy.product'),
        ),
    ]
