# Generated by Django 3.1.7 on 2021-04-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0002_auto_20210426_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlog',
            name='isCancle',
            field=models.BooleanField(default=False),
        ),
    ]
