# Generated by Django 3.1.7 on 2021-04-26 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0003_orderlog_iscancle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlog',
            old_name='isCancle',
            new_name='isCancel',
        ),
    ]
