# Generated by Django 3.1.7 on 2021-05-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0004_auto_20210426_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MyPerson',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dummy.person',),
        ),
    ]
