# Generated by Django 3.1.7 on 2021-05-03 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0005_myperson_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedPerson',
            fields=[
            ],
            options={
                'ordering': ['last_name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dummy.person',),
        ),
    ]
